language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
#  - "nightly" # splinter fails currently for nightly, so as we don't really need nightly support...
install:
  - python setup.py install
script:
  - python setup.py test
